apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts-table-app
  labels:
    app: contacts-table-app
spec:
  replicas: 1                 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: contacts-table-app
  template:
    metadata:
      labels:
        app: contacts-table-app
    spec:
      containers:
      - name: contacts-table-app
        image: adamrab/contacts-table:latest  # Specify the correct image and tag
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_HOST
        - name: MYSQL_PORT
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_PORT
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_DATABASE
        resources:                    # Optionally specify resource requests/limits
          limits:
            memory: "1Gi"
            cpu: "2"
          requests:
            memory: "512Mi"
            cpu: "1"
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
      imagePullSecrets:
      - name: regcred  # Docker registry secret
---
apiVersion: v1
kind: Service
metadata:
  name: contacts-table-service
spec:
  type: LoadBalancer               # Change to NodePort if you want to expose it locally
  selector:
    app: contacts-table-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
